Add global formatting (`Prettier`).
0xFableOrg/0xFable pull request #130
Opened 2024-02-27 11:26 UTC by ultraviolet10

Adds a global format command that runs prettier's `--write` on all specified file types. 

Uses the following options within the config (`prettierrc.json`):

- `"semi": false,`: doesn't add semicolons on save
- `"trailingComma": "es5",`: https://prettier.io/docs/en/options.html#trailing-commas
- `"singleQuote": false,`: uses double quotes for imports/elsewhere.
- `"tabWidth": 2,`: @norswap did you want this as 4? 
- `"useTabs": true,`: https://prettier.io/docs/en/options.html#tabs
- `"printWidth": 100`: increase the number of characters that prettier will try to wrap around, prevents the dependency arrays of `useEffect` and `useCallback` hooks from splitting into a column unless absolutely needed (https://prettier.io/docs/en/options.html#print-width).

2024-03-01 05:13 UTC, ultraviolet10 commented
there's another interesting plugin we could use: https://www.npmjs.com/package/eslint-plugin-simple-import-sort

this helps sort imports in different files according to your specs, here's an example one: 

```
"simple-import-sort/imports": [
      "error",
      {
        "groups": [
          // Packages. `react` related packages come first.
          [
            "^react",
            "^next",
            "@metamask|@walletconnect|clsx|@reduxjs|async-mutex|flowbite-react|redux-persist|pubnub|redux",
            "^(ethers|google|lodash|bn.js|styled-components|child_process|cluster|console|constants|crypto|dgram|dns|domain|events|fs|http|https|module|net|os|path|punycode|querystring|readline|repl|stream|string_decoder|sys|timers|tls|tty|url|util|vm|zlib|freelist|v8|process|async_hooks|http2|perf_hooks)"
          ],
          // Internal packages.
          ["^@?\\w"],
          // Parent imports. Put `..` last.
          ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
          // Other relative imports. Put same-folder imports and `.` last.
          ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
          // Style imports.
          ["^.+\\.s?css$"],
          // Side effect imports.
          ["^\\u0000"]
        ]
      }
      ```

2024-03-01 05:15 UTC, ultraviolet10 commented
As well as: https://github.com/tailwindlabs/prettier-plugin-tailwindcss

2024-03-01 22:18 UTC, norswap commented
> `"tabWidth": 2`: @norswap did you want this as 4?

Yes let's go for 4!

> "useTabs": true: https://prettier.io/docs/en/options.html#tabs

This is always religious, but I do prefer spaces myself. I guess with prettier it matters less, but it ensures proper display on Github for instance.

Any counter here? Like would you strongly prefer a 2 or 8 spaces local display?

2024-03-01 22:28 UTC, norswap requested changes

2024-03-01 22:28 UTC, norswap commented on .github/workflows/check.yaml
> +        run: cd packages/webapp && pnpm install
this should be covered by `make setup` above I believe

2024-03-01 22:28 UTC, norswap commented on .github/workflows/check.yaml
> +        run: cd packages/webapp && npx prettier --check "**/*.{js,jsx,ts,tsx,json,css}"
This should be folded into `make check` in the webapp Makefile (which will cause it be checked by the global Makefile `make check` and thus covered by the above)

2024-03-01 22:28 UTC, norswap commented on Makefile
> +	cd packages/contract && make check
```suggestion
	cd packages/contract && make format
```

2024-03-01 22:28 UTC, norswap commented on packages/webapp/Makefile
> +	npx prettier --write "**/*.{js,jsx,ts,tsx,json,css}"
```suggestion
	pnpm prettier --write "**/*.{js,jsx,ts,tsx,json,css}"
```

2024-03-02 11:23 UTC, ultraviolet10 commented
> > `"tabWidth": 2`: @norswap did you want this as 4?
> 
> Yes let's go for 4!
> 
> > "useTabs": true: https://prettier.io/docs/en/options.html#tabs
> 
> This is always religious, but I do prefer spaces myself. I guess with prettier it matters less, but it ensures proper display on Github for instance.
> 
> Any counter here? Like would you strongly prefer a 2 or 8 spaces local display?

No hard preference here, 4 is good!

2024-03-02 21:19 UTC, norswap approved these changes
Approving, but address comments!

2024-03-02 21:19 UTC, norswap commented on packages/webapp/.prettierrc.json
isn't 150 too much? I like 100 or 120

2024-03-02 21:19 UTC, norswap commented on packages/webapp/Makefile
> +.PHONY: check
you can put both of these on different lines (no need for &&)

2024-03-03 03:30 UTC, merged