Adding Player Handles
0xFableOrg/0xFable pull request #136
Opened 2024-05-20 14:38 UTC by faytey

## Context (Problem, Motivation, Solution)

Link related issues!
Issue [117](https://github.com/0xFableOrg/0xFable/issues/117)

## Describe Your Changes
I added the smart contract to implement Player handles and wrote the tests to check the functions work properly

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I ran `make check` and fixed resulting issues
- [ ] I ran the relevant tests and they all pass
- [ ] I wrote tests for my new features, or added regression tests for the bug I fixed

## Testing

If you didn't write tests, explain how you made sure the code was correct and working as intended.

2024-05-20 14:45 UTC, faytey commented
I need your review on this before proceeding, I'm encountering errors setting up the web

2024-05-28 22:38 UTC, faytey commented
> I need your review on this before proceeding @norswap , Also I'm encountering errors setting up the webapp

Hello @norswap still awaiting your review

2024-06-08 22:29 UTC, norswap requested changes
Great work! Sorry again for the delay. Could you make the requested changes? I'll make sure to prioritize reviewing them now.

2024-06-08 22:29 UTC, norswap commented on package-lock.json
Could you remove this file? We use `pnpm` for package management and we already have a pnpm-lock file in place!

2024-06-08 22:29 UTC, norswap commented on packages/contracts/src/PlayerHandle.sol
> +        require(handleOwners[newHandle] == address(0), "Handle already taken");
Could you use custom errors for those?

2024-06-08 22:29 UTC, norswap commented on packages/contracts/src/PlayerHandle.sol
> +    function getEnsName(address addr) external view returns (string memory);
That doesn't seem to be the actual ENS resolver interface, which uses `name()` for lookups, see here: https://docs.ens.domains/resolvers/public

We also probably won't deploy on Ethereum, which is the only chain that has this resolver at the moment. ENS has announced that L2 support is coming but it's not there yet. I think it's fine to keep the resolver interface for now, at worst we can stub it with a permissioned registry that we sign on — let's just make the interface the same as the real thing.

2024-06-08 22:29 UTC, norswap commented on packages/contracts/src/PlayerHandle.sol
> +            if (char < 0x20 || char > 0x7E || char == 0x2E) {
Note to myself: will probably want to change this to only support alphanumerics & dashes, underscores, square brackets (for cute clan names), spaces (but not more than one in a row, and not at the end or at the start of the handle), as well as put a max character limit.

Fine to leave this as is for this PR.

2024-06-08 22:29 UTC, norswap commented on packages/contracts/src/test/PlayerHandle.t.sol
> +}
Could you spin this out in a separate file (in the test repo), and add a deployment of this + `PlayerHandle` to the `Deploy.s.sol`? You'll also want to add an entry for `PlayerHandle` in `deployment.ts` on the frontend.

2024-07-01 19:47 UTC, faytey commented
Hi Sir I'd get started on these and update, sorry for the delay

2024-07-03 12:40 UTC, custosDiretriz commented
Hi Sir, I've made the necessary corrections and pushed

2024-07-03 12:44 UTC, faytey commented
Hi Sir, I have made requested corrections

2024-07-03 19:09 UTC, norswap commented
Also it seems you've made changes to the lockfile, could just revert it to the master version so that no changes show? The current file seems incorrect in some way, as shown by the failing CI check.

2024-07-03 19:40 UTC, faytey commented
> Also it seems you've made changes to the lockfile, could just revert it to the master version so that no changes show? The current file seems incorrect in some way, as shown by the failing CI check.

Hi Sir, I didn't make any changes to the lockfile and can't seem to understand how to rectify it.

2024-07-03 19:56 UTC, norswap commented
That was probably accidental, you can see it is changed in "Files changes" here on Github.

Fixing it requires a little bit of git foo:
You can revert it by using `git checkout master -- pnpm-lock.yaml` then `git add pnpm-lock.yaml`.
You could then git commit and push that, but let's squash all your commit together:
`git reset --soft HEAD~7 && git commit`

(The 7 here is the number of commits you've made, so if you add additional commits in between you need to update that number.)

Then finally `git push --force-with-lease` to replace the commits here with the single squashed commit.

2024-07-03 20:55 UTC, faytey commented
> That was probably accidental, you can see it is changed in "Files changes" here on Github.
> 
> Fixing it requires a little bit of git foo: You can revert it by using `git checkout master -- pnpm-lock.yaml` then `git add pnpm-lock.yaml`. You could then git commit and push that, but let's squash all your commit together: `git reset --soft HEAD~7 && git commit`
> 
> (The 7 here is the number of commits you've made, so if you add additional commits in between you need to update that number.)
> 
> Then finally `git push --force-with-lease` to replace the commits here with the single squashed commit.

done sir

2024-07-06 10:01 UTC, faytey commented
Hello sir @norswap

2024-07-21 17:45 UTC, norswap commented
Thanks! Did some extra cleanup and merged here: https://github.com/0xFableOrg/0xFable/pull/137

2024-07-21 17:45 UTC, closed without merging